tare_planner_node:
  ros__parameters:
    sub_start_exploration_topic_ : /start_exploration
    sub_terrain_map_topic_ : /terrain_map
    sub_terrain_map_ext_topic_ : /terrain_map_ext
    sub_state_estimation_topic_ : /state_estimation_at_scan
    sub_registered_scan_topic_ : /registered_scan
    sub_coverage_boundary_topic_ : /sensor_coverage_planner/coverage_boundary
    sub_viewpoint_boundary_topic_ : /navigation_boundary
    sub_nogo_boundary_topic_ : /sensor_coverage_planner/nogo_boundary
    sub_joystick_topic_ : /joy
    sub_reset_waypoint_topic_ : /reset_waypoint
    pub_exploration_finish_topic_ : exploration_finish
    pub_runtime_breakdown_topic_ : runtime_breakdown
    pub_runtime_topic_ : /runtime
    pub_waypoint_topic_ : /way_point
    pub_momentum_activation_count_topic_ : momentum_activation_count

    kAutoStart : true
    kRushHome : true
    kUseTerrainHeight : true
    kCheckTerrainCollision : true
    kExtendWayPoint : false
    kUseLineOfSightLookAheadPoint : false
    kNoExplorationReturnHome : false
    kExtendWayPointDistanceBig : 8.0
    kExtendWayPointDistanceSmall : 3.5
    kKeyposeCloudDwzFilterLeafSize : 0.2
    kRushHomeDist : 1.0
    kAtHomeDistThreshold : 0.75
    kTerrainCollisionThreshold : 0.5
    kLookAheadDistance : 8.0
    kUseMomentum : false 
    kDirectionChangeCounterThr : 6
    kDirectionNoChangeCounterThr : 5
    kResetWaypointJoystickAxesID : 2

    # PlanningEnv
    kUseFrontier : true
    kFrontierClusterTolerance : 5.0
    kFrontierClusterMinSize : 1
    kUseCoverageBoundaryOnFrontier : false
    kUseCoverageBoundaryOnObjectSurface : false

    # Rolling occupancy grid
    rolling_occupancy_grid/resolution_x : 0.2
    rolling_occupancy_grid/resolution_y : 0.2
    rolling_occupancy_grid/resolution_z : 0.2

    kSurfaceCloudDwzLeafSize : 0.1
    kCollisionCloudDwzLeafSize : 0.1
    kKeyposeCloudStackNum : 10
    kPointCloudRowNum : 20
    kPointCloudColNum : 20
    kPointCloudLevelNum : 30
    kMaxCellPointNum : 10000
    kPointCloudCellSize : 10.0
    kPointCloudCellHeight : 0.5
    kPointCloudManagerNeighborCellNum : 5
    kCoverCloudZSqueezeRatio : 2.0

    # KeyposeGraph
    keypose_graph/kAddNodeMinDist : 1.0
    keypose_graph/kAddNonKeyposeNodeMinDist : 0.5
    keypose_graph/kAddEdgeConnectDistThr : 3.0
    keypose_graph/kAddEdgeToLastKeyposeDistThr : 3.0
    keypose_graph/kAddEdgeVerticalThreshold : 1.0
    keypose_graph/kAddEdgeCollisionCheckResolution : 0.4
    keypose_graph/kAddEdgeCollisionCheckRadius : 0.4
    keypose_graph/kAddEdgeCollisionCheckPointNumThr : 1

    # ViewPointManager
    viewpoint_manager/number_x : 20 # 50
    viewpoint_manager/number_y : 20 # 50
    viewpoint_manager/number_z : 1
    viewpoint_manager/resolution_x : 0.2 # 0.4
    viewpoint_manager/resolution_y : 0.2 # 0.4
    viewpoint_manager/resolution_z : 0.0
    kConnectivityHeightDiffThr : 0.25
    kGreedyViewPointSampleRange : 2 # 3
    kLocalPathOptimizationItrMax : 5 # 10
    kViewPointCollisionMargin : 0.2  # 0.6
    kViewPointCollisionMarginZPlus : 0.5
    kViewPointCollisionMarginZMinus : 0.5
    kCollisionGridZScale : 1.0
    kCollisionGridResolutionX : 0.2
    kCollisionGridResolutionY : 0.2
    kCollisionGridResolutionZ : 0.0
    kCollisionPointThr : 1
    kLineOfSightStopAtNearestObstacle : true
    kViewPointHeightFromTerrain : 0.3  # 0.75
    kViewPointHeightFromTerrainChangeThreshold : 0.2  # 0.6
    kCheckDynamicObstacleCollision : false
    kCollisionFrameCountMax : 3

    kSensorRange : 8.5  # 3.5
    kNeighborRange : 3.0
    kCoverageOcclusionThr : 0.3
    kCoverageDilationRadius : 0.5

    # Grid World
    kGridWorldXNum : 50 # 121
    kGridWorldYNum : 50 # 121
    kGridWorldZNum : 50 # 121
    kGridWorldCellHeight : 1.5 # 3.0
    kGridWorldNearbyGridNum : 2
    kMinAddPointNumSmall : 1 # 30
    kMinAddPointNumBig : 5 #60
    kMinAddFrontierPointNum : 1 #20
    kCellExploringToCoveredThr : 1
    kCellCoveredToExploringThr: 2 # 10
    kCellExploringToAlmostCoveredThr: 2 # 10
    kCellAlmostCoveredToExploringThr: 4 # 20
    kCellUnknownToExploringThr: 1

    # Visualization (parameters not working I think)
    kExploringSubspaceMarkerColorGradientAlpha : true
    kExploringSubspaceMarkerColorMaxAlpha : 0.8
    kExploringSubspaceMarkerColorR : 0.0
    kExploringSubspaceMarkerColorG : 1.0
    kExploringSubspaceMarkerColorB : 0.0
    kExploringSubspaceMarkerColorA : 1.0
    kLocalPlanningHorizonMarkerColorR : 0.0
    kLocalPlanningHorizonMarkerColorG : 1.0
    kLocalPlanningHorizonMarkerColorB : 0.0
    kLocalPlanningHorizonMarkerColorA : 1.0
    kLocalPlanningHorizonMarkerWidth : 0.05
    kLocalPlanningHorizonHeight : 3.0
